<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKICV8Yr\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKICV8Yr/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKICV8Yr.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKICV8Yr\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKICV8Yr\appAppKernelProdContainer([
    'container.build_hash' => 'KICV8Yr',
    'container.build_id' => '8213f233',
    'container.build_time' => 1758375704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKICV8Yr');
